# Generated by Django 5.1.4 on 2026-04-10 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('fee_currency', models.CharField(default='USD', max_length=5)),
                ('template_fields', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'instrument_types',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('face_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('issued', 'Issued'), ('active', 'Active'), ('matured', 'Matured'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('receiving_bank', models.CharField(blank=True, max_length=255)),
                ('bank_swift_code', models.CharField(blank=True, max_length=20)),
                ('beneficiary_name', models.CharField(blank=True, max_length=255)),
                ('beneficiary_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='customers.customer')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_instruments', to=settings.AUTH_USER_MODEL)),
                ('instrument_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='instruments.instrumenttype')),
            ],
            options={
                'db_table': 'instruments',
                'ordering': ['-created_at'],
            },
        ),
    ]
