# Generated by Django 5.1.4 on 2026-04-10 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_address', models.CharField(blank=True, max_length=500)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_address', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'beneficiaries',
                'db_table': 'beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending_review', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='transfers.beneficiary')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='customers.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='banking.bankaccount')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfer_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
